language: python

python:
  - "3.3"

install:
  - pip install -r requirements.txt
  - pip install pyflakes

  # Install most recent beanstalkd from source
  - wget https://github.com/kr/beanstalkd/archive/v1.9.tar.
  - tar xfv v1.9.tar.gz
  - make -C beanstalkd-1.9
  - mv beanstalkd-1.9/beanstalkd .
  # Install Python dependencies
  - pip install -r .travis-requirements.txt --use-mirrors
  - beanstalkd -l 127.0.0.1 -p 11300 &


script:
  - pyflakes .
  - python runtests.py -v

branches:
    only:
        - master
        - dev
